/**
 * @file Request.h
 * @brief Defines the Request structure representing a simulated web request.
 *
 * A Request models an incoming client job handled by the load balancer.
 * Each request contains network information, processing requirements,
 * job type, and timing data used to measure system performance.
 */

#pragma once
#include <string>

/**
 * @struct Request
 * @brief Represents a single web request in the load balancer simulation.
 *
 * Requests are generated by the simulation, filtered by the firewall,
 * queued by the load balancer, processed by web servers, and tracked
 * using timing metadata for performance statistics.
 */
struct Request {

    /** @brief Source IP address of the incoming request. */
    std::string ipIn;

    /** @brief Destination IP address associated with the request response. */
    std::string ipOut;

    /** @brief Number of clock cycles required to process this request. */
    int timeRequired = 0;

    /**
     * @brief Type of job requested.
     *
     * 'P' represents a processing job, while 'S' represents a streaming job.
     * This field is used by the Switch to route requests to the appropriate
     * load balancer.
     */
    char jobType = 'P';

    /** @brief Simulation cycle when the request arrived at the load balancer. */
    int arrivalTime = 0;

    /** @brief Simulation cycle when processing of the request began. */
    int startTime = -1;

    /** @brief Simulation cycle when processing of the request completed. */
    int finishTime = -1;
};